"""Build the QEMU argv for a Machine and render it as run.command / run.bat.

Pure: no Tk, no filesystem access beyond string handling. The GUI renders
for the platform it runs on; tests pass ``platform=`` explicitly
(``"darwin"``, ``"win32"``, ``"linux"``).

QEMU itself parses ``vendor=X,product=Y Z``; the shell quoting produced
here only keeps each token whole. One argv list, two renderings.
"""

from __future__ import annotations

import shlex

from . import paths
from .model import Machine

HEADER_NOTE = ("Generated by Qemu-GUI from machine.json. Hand edits are lost: "
               "this file is rewritten every time the machine is saved or started.")

AUDIO_DEFAULT = {"darwin": "coreaudio", "win32": "dsound"}


def qopt(value: str) -> str:
    """Escape a value for QEMU's key=value option parser (comma -> ,,)."""
    return str(value).replace(",", ",,")


def _path(p: str, base: str, platform: str) -> str:
    """Absolute path for *platform*; relative values resolve against *base*."""
    return paths.join_path(base, p, platform)


def split_extra_args(text: str, platform: str = paths.HOST_PLATFORM) -> list[str]:
    """Tokenise the free-text extra arguments line. On Windows backslashes are
    path separators, not escapes, so escape processing is disabled there."""
    text = (text or "").strip()
    if not text:
        return []
    lex = shlex.shlex(text, posix=True)
    lex.whitespace_split = True
    lex.commentchars = ""
    if paths.is_windows(platform):
        lex.escape = ""
    return list(lex)


def governor_option(m: Machine) -> str:
    g = m.governor
    if g.mode == "off":
        return f"{m.machine},calibration-governor=off"
    if g.mode == "mips":
        return f"{m.machine},calibration-governor=mips={int(g.mips)}"
    return m.machine


def build_argv(m: Machine, qemu_dir: str, machine_dir: str,
               platform: str = paths.HOST_PLATFORM) -> list[str]:
    """The complete argv, first token = absolute path of the QEMU binary."""
    qd = m.effective_qemu_dir(qemu_dir)
    argv: list[str] = [paths.join_path(qd, paths.qemu_binary_name(platform), platform)]

    argv += ["-M", governor_option(m)]
    argv += ["-m", str(int(m.ram_mb))]
    argv += ["-bios", _path(m.rom, qd, platform)]
    argv += ["-display", m.display]

    audio = m.audio
    if audio == "default":
        audio = AUDIO_DEFAULT.get(platform, "sdl")
    argv += ["-audiodev", f"{audio},id=snd", "-global", "awacs.audiodev=snd"]

    if m.onboard_romfile:
        argv += ["-global", f"ati-mach64-gt.romfile={qopt(_path(m.onboard_romfile, qd, platform))}"]

    if m.second_gpu and m.second_gpu.device:
        parts = [m.second_gpu.device]
        if m.second_gpu.addr:
            parts.append(f"addr={m.second_gpu.addr}")
        if m.second_gpu.romfile:
            parts.append(f"romfile={qopt(_path(m.second_gpu.romfile, qd, platform))}")
        argv += ["-device", ",".join(parts)]

    if m.network.mode == "none":
        argv += ["-nic", "none"]
    else:
        argv += ["-nic", f"user,model=bmac,mac={m.network.mac}"]

    for index, d in enumerate(m.ata):
        if d is None:
            continue
        media = "cdrom" if d.kind == "cdrom" else "disk"
        argv += ["-drive", f"file={qopt(_path(d.file, machine_dir, platform))},"
                           f"format={d.format or 'raw'},media={media},index={index}"]

    for s in sorted(m.scsi, key=lambda x: x.id):
        prefix = "scd" if s.kind == "cdrom" else "shd"
        drive_id = f"{prefix}{s.id}"
        dev = "scsi-cd" if s.kind == "cdrom" else "scsi-hd"
        argv += ["-drive", f"file={qopt(_path(s.file, machine_dir, platform))},"
                           f"format={s.format or 'raw'},if=none,id={drive_id}"]
        tok = f"{dev},drive={drive_id},scsi-id={s.id}"
        if s.identity:
            ident = s.identity
            tok += (f",vendor={qopt(ident.vendor)},product={qopt(ident.product)},"
                    f"ver={qopt(ident.ver)}")
        argv += ["-device", tok]

    if m.floppy and m.floppy.file:
        argv += ["-drive", f"if=none,id=fd,file={qopt(_path(m.floppy.file, machine_dir, platform))},"
                           f"format={m.floppy.format or 'raw'}",
                 "-global", "swim3.drive=fd"]

    argv += split_extra_args(m.extra_args, platform)
    return argv


def group_options(argv: list[str]) -> list[list[str]]:
    """Group [binary, -opt, value, -opt, ...] into one list per option so
    each option lands on its own line in the rendered launcher."""
    groups: list[list[str]] = []
    for tok in argv[1:]:
        if tok.startswith("-") or not groups:
            groups.append([tok])
        else:
            groups[-1].append(tok)
    return groups


def render_shell(argv: list[str]) -> str:
    lines = ["#!/bin/bash",
             f"# {HEADER_NOTE}",
             'cd "$(dirname "$0")"',
             "",
             shlex.quote(argv[0]) + " \\"]
    groups = group_options(argv)
    for i, g in enumerate(groups):
        cont = " \\" if i < len(groups) - 1 else ""
        lines.append(" ".join(shlex.quote(t) for t in g) + cont)
    return "\n".join(lines) + "\n"


def bat_quote(token: str) -> str:
    """cmd.exe quoting: whole-token double quotes when the token contains a
    space or a comma (contract rule); '%' must be doubled in a .bat file."""
    t = token.replace("%", "%%")
    if (" " in t or "," in t) and not (t.startswith('"') and t.endswith('"')):
        return f'"{t}"'
    return t


def render_bat(argv: list[str]) -> str:
    lines = ["@echo off",
             f"rem {HEADER_NOTE}",
             'cd /d "%~dp0"',
             "",
             bat_quote(argv[0]) + " ^"]
    groups = group_options(argv)
    for i, g in enumerate(groups):
        cont = " ^" if i < len(groups) - 1 else ""
        lines.append(" ".join(bat_quote(t) for t in g) + cont)
    return "\r\n".join(lines) + "\r\n"


def render_launcher(argv: list[str], platform: str = paths.HOST_PLATFORM) -> str:
    return render_bat(argv) if paths.is_windows(platform) else render_shell(argv)


def launcher_text(m: Machine, qemu_dir: str, machine_dir: str,
                  platform: str = paths.HOST_PLATFORM) -> str:
    return render_launcher(build_argv(m, qemu_dir, machine_dir, platform), platform)


def write_launcher(m: Machine, qemu_dir: str, machine_dir: str,
                   platform: str = paths.HOST_PLATFORM):
    """Write run.command / run.bat into the machine folder; returns (path, argv)."""
    from pathlib import Path
    import os
    import stat
    argv = build_argv(m, qemu_dir, machine_dir, platform)
    text = render_launcher(argv, platform)
    path = Path(machine_dir) / paths.launcher_name(platform)
    path.write_text(text, encoding="utf-8", newline="")
    if not paths.is_windows(platform):
        st = os.stat(path)
        os.chmod(path, st.st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return path, argv
